Repository EndersonMarques/game-ip, pull requests merged in 2021-12, with the labels that each got.

#2 Feito a tela de Menu, e o gerenciamento de telas do jogo :D
  assets/banner.png
  main.c
Labels: development

#3 add loading em menu and musicg
  assets/intro.mp3
  assets/loading-bar.png
  main.c
Labels: development

#6 Center itens menu
  main.c
Labels: enhancement

#11 Tela final
  assets/lose-telafinal.png
  main.c
Labels: development

#12 add pista e carro
  assets/Car-azul.png
  assets/pista.png
  assets/road.png
  main.c
Labels: development

#13 adicionado movimento vertical do carro
  assets/sprite_brt2.png
  main.c
Labels: development

#17 apresentavel
  assets/cashSound.mp3
  main.c
Labels: bug, enhancement, development
